### ISSUE TITLE
AttributeError: 'GenerationsResource' object has no attribute 'image'

### ISSUE THREAD

**Issue by carat-keeeehun** [lumalabs/ComfyUI-LumaAI-API#5]
When I test the image generation workflow in workflows directory, I encountered below issue.

```
!!! Exception during processing !!! 'GenerationsResource' object has no attribute 'image'
Traceback (most recent call last):
  File "/home/comfyui/comfyui/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/comfyui/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/comfyui/comfyui/custom_nodes/ComfyUI-LumaAI-API/py/lumaai_api_node.py", line 556, in run
    generation = client.generations.image.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GenerationsResource' object has no attribute 'image'
```

**Comment by pedrogengo** [comment]
Looks like you are using an old version of lumaai package. Can you please update it by running `pip install -U lumaai`? Tks!

**Comment by pedrogengo** [comment]
Closing due to inactivity
